// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Standardizing storage and adding detection flags to prevent "Lock" hangs
    storage: window.localStorage, 
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Helps with session recovery after sign-in
    flowType: 'pkce', // Modern, more secure flow that handles locks better
  }
});